### ISSUE TITLE
wh-adverbs questionnaire

### ISSUE THREAD

**Issue by olzama** [delph-in/matrix#567]
A bug and a presentation issue:

(1) Bug: The predicate autofill for question adverbs has _a_ instead of _n_ prefilled. So currently the user needs to manually correct: _place_n_rel etc.

(2) Minor presentation issue (typo): "location in time/place space" should just be "location in time/space".

**Comment by ajcassell** [comment]
@emilymbender (2) does not exist anymore
I am uncertain (1) is possible/warranted. It's possible to change all the adverb prefills to be n but I'm assuming non-question adverbs are supposed to be a, correct? If so, I have tried to update the predicate to have n instead of a when the question box is checked. However, I think in general the user is likely to enter the spelling first before checking the box which would. Once the spelling is filled out once, it does not automatically refill the pred each time it is updated. This is true of the entire questionnaire. So my question is whether it might be more beneficial to write a note on the page that question adverbs need updated predicates?

**Comment by emilymbender** [comment]
Agreed that this is best handled through documentation.

**Comment by emilymbender** [comment]
I suppose we could do it via validation, too, giving a ? if someone has _a_rel in the PRED for a wh adverb.
