### ISSUE TITLE
Type without supertype, in adnominal possession library

### ISSUE THREAD

**Issue by emilymbender** [delph-in/matrix#598]
The attached choices file generates a grammar which includes the following:

poss-unary-phrase-1 := [ SYNSEM.LOCAL.CAT.HEAD.SPEC-INIT + ].

To investigate:
1) Should this actually be a type addendum statement, with :+ instead of :=?
2) If not, what should the supertype be?

[poss-bug.txt](https://github.com/delph-in/matrix/files/6174517/poss-bug.txt)

**Comment by ltxom** [comment]
Found a [good choices file](https://github.com/delph-in/matrix/blob/trunk/tests/regression/choices/adnom-poss-frr) that can generate the same type with supertype:

```
poss-unary-phrase-1 := poss-unary-phrase &
  [ ARGS < [ SYNSEM.LOCAL.CAT.HEAD.POSSESSOR possessor-1 ] >,
    SYNSEM.LOCAL.CAT [ HEAD.SPEC-INIT +,
                       VAL.SPEC.FIRST.LOCAL.CAT.POSSESSUM nonpossessive ] ].
```

Investigating why the buggy choice doesn't...

**Comment by ltxom** [comment]
Here's my finding:
The adnom-poss library reads adnom-poss section and calls [customize_poss_rules()](https://github.com/delph-in/matrix/blob/trunk/gmcs/linglib/adnominal_possession.py#L343) function. If there is possessive strategy that mod-spec=spec, it will assign default TDL in [line 499](https://github.com/delph-in/matrix/blob/trunk/gmcs/linglib/adnominal_possession.py#L499):
`poss-unary-phrase-1 := [ SYNSEM.LOCAL.CAT.HEAD.SPEC-INIT + ].`

The supertype of poss-unary-phrase is only defined if the possessive strategy is used in morphology. For example, the supertype is well defined by adding the following morphology definition to the buggy choice:
```
 noun-pc1_name=possessive
  noun-pc1_obligatory=on
  noun-pc1_order=suffix
  noun-pc1_inputs=noun
    noun-pc1_lrt1_name=possessor
      noun-pc1_lrt1_feat1_name=poss-strat1
      noun-pc1_lrt1_feat1_value=possessor
      noun-pc1_lrt1_feat1_head=itself
      noun-pc1_lrt1_lri1_inflecting=yes
      noun-pc1_lrt1_lri1_orth=s
```
This is because the [customize_possessor_irules() function](https://github.com/delph-in/matrix/blob/trunk/gmcs/linglib/adnominal_possession.py#L674) is called only if it's defined in morphology. The supertype is added in this function in [line 711](https://github.com/delph-in/matrix/blob/trunk/gmcs/linglib/adnominal_possession.py#L711).

**Comment by ltxom** [comment]
Should we add an additional validation process for this type of choices files (showing an error when a defined poss-start is not used anywhere else)? Or should we move the supertype definition earlier (before reading the morphology section)?

**Comment by emilymbender** [comment]
I think the most user-friendly thing would be to do

1) A warning (?) rather than an error (*) from the validation system
2) Define the supertype in this case, even though it's not instantiated in the morphology

This way people can still get grammars that compile, but also have the information that this analysis is incomplete.

**Comment by ltxom** [comment]
OK! I will try to implement both solutions. Do I need to create a regression test since it doesn't have any morphology to test?

**Comment by emilymbender** [comment]
Yes, it would be good to create a regression test. In this case, we're mainly testing for that the grammar compiles, but for form's sake, the regression test could have one simple sentence in it. 

Is there a place to put comment strings for the regression tests? It might be good to indicate this there.

**Comment by ltxom** [comment]
Got it! 

Yes, I can add a [description ](https://github.com/delph-in/matrix/blob/trunk/tests/regression/regression-test-index)for the regression tests.
