### ISSUE TITLE
Too many values in trigger rules

### ISSUE THREAD

**Issue by emilymbender** [delph-in/matrix#599]
Many of the choices files created for Ling 567 in 2021 gave trigger rules like this:

ki_3_gr := arg0e_gtr &
  [ CONTEXT.RELS.LIST < [ ARG0.E [ TENSE fut,
                                   ASPECT pot,
                                   MOOD oblig,
                                   cond  ] ] >,
    FLAGS.TRIGGER "ki_3" ].

... which lead to grammars that don't load.

**Comment by emilymbender** [comment]
This seems to happen when the TAM features are specified on the auxiliary, rather than its complement. The attached choices file illustrates the behavior.
[choices.txt](https://github.com/delph-in/matrix/files/14489925/choices.txt)

**Comment by ajcassell** [comment]
@emilymbender So looking at this choices file, this grammar wouldn't load in the LKB because of this issue that I recently put in validation for: https://github.com/delph-in/matrix/issues/464
When I make aux1_subj=np instead of aux1_subj=np-comp-case to pass validation, I am able to load the resulting grammar in the LKB. This makes me think this issue is not related to TAM features on the auxiliary. However, if TAM features on the aux rather than complement is a true issue, perhaps we could morph this issue into that?

**Comment by emilymbender** [comment]
What do the generated trigger rules look like in the grammar that can load?

**Comment by ajcassell** [comment]
I am actually seeing identical trigger.mtr files for the choices file above using the live site right now and the test site with my change to np-comp-case.
<img width="547" alt="Screen Shot 2024-11-12 at 4 44 39 PM" src="https://github.com/user-attachments/assets/de19345e-6f4a-451c-b3a7-501359d0f4d9">

**Comment by emilymbender** [comment]
So that trigger rule is broken -- there should be one value for TENSE that is the shared supertype of present & future. If that supertype isn't already created, the production of the trigger rule should also involve creating it.

**Comment by ajcassell** [comment]
I see. That supertype is not already created from what I see. The choices/customization site show past, present, and future as the three tenses. The reason they show up together in the trigger rule is because it's populated directly from the choices i.e. ```    aux1_feat1_name=tense
    aux1_feat1_value=present, future
    aux1_feat1_head=verb```
I don't know if there are any restrictions on which combination of tenses are allowed on a feature, but what should the supertype be? Can it be nonpast (also one of the options that is not selected on the TAM page)? Furthermore, would we need to add a supertype for each combination of tenses?

**Comment by emilymbender** [comment]
There are functions in the code that calculate the mutual supertype and create it if need be. That function should be invoked here.
