### ISSUE TITLE
matrix link

### ISSUE THREAD

**Issue by arademaker** [delph-in/matrix#609]
The online MATRIX system is offline. The link in [here](https://github.com/delph-in/docs/wiki/MatrixGettingStarted#where-is-the-matrix) is  http://matrix.delph-in.net/customize/matrix.cgi and it is not working

The link called `customization page` in https://github.com/delph-in/docs/wiki/MatrixTop points to http://www.delph-in.net/matrix/customize/matrix.cgi does not work too.

Can I have MATRIX running locally? How? 

Can MATRIX generate the startup scripts for ACE besides the scripts for LKB? How?

**Comment by olzama** [comment]
I think it will be back online soon (it sometimes goes offline...)

There is a copy here: https://matrix.ling.washington.edu/trunktest/matrix.cgi

Yes, it can of course be set up locally though you need to be well-versed in apache :). Just copy the files from the matrix repository to where you want them; matrix.cgi will be among them. I myself couldn't set it up (because I am completely hopeless with servers). But there is nothing special apart from the fact that there is a server involved in running a cgi file.

For ace, see here: https://github.com/delph-in/docs/wiki/AceUse

`ace -G grammar.dat -g path-to/config.tdl`

-- for Matrix-derived grammars, you will find the `config.tdl` in the folder named `ace`.

**Comment by arademaker** [comment]
I see, I know how to compile the grammar, what I didn't know is that a `ace` folder is also produced. I will ask @leoalenc to add it in our repo.
