### ISSUE TITLE
Update wiki links in Matrix customization questionnaire

### ISSUE THREAD

**Issue by emilymbender** [delph-in/matrix#619]
The Grammar Matrix customization questionnaire includes links to the MatrixDoc pages as well as at least one other link to the old DELPH-IN wiki (http://wiki.delph-in.net/moin/VersionControlForGrammarDevelopment, on the General Information page). These should all be located and updated to point to the new wiki on github.

**Comment by ajcassell** [comment]
@emilymbender I've checked the code and these are all of the links on the General Information page, which seems to show they have all been updated. 

https://github.com/delph-in/docs/wiki/ReppTop
https://github.com/delph-in/docs/wiki/RmrsPos>DELPH-IN
https://github.com/delph-in/docs/wiki/VersionControlForGrammarDevelopment

http://www.sil.org/iso639-3/codes.asp
http://www.sil.org/computing/toolbox

However those two ^ SIL links do not work for me.

**Comment by emilymbender** [comment]
I can't actually get to https://matrix.ling.washington.edu/customize/matrix.cgi right now ("internal server error"). Can you send me the textual context for those two SIL links?

**Comment by ajcassell** [comment]
Oh that was definitely something I meant to bring up today as well. I haven't been able to get to the site for a few days now.. probably since late last week. 

The first is for the ISO code on General Information and the second is for the Toolbox Import page.
<img width="1134" alt="Screen Shot 2024-10-08 at 4 58 48 PM" src="https://github.com/user-attachments/assets/76e37a02-82f9-41f9-94bf-738947b531ae">
<img width="560" alt="Screen Shot 2024-10-08 at 4 59 00 PM" src="https://github.com/user-attachments/assets/260b450f-811b-4ef7-a33a-7634c60d18cf">

**Comment by emilymbender** [comment]
Ah okay. The first should be: https://iso639-3.sil.org/code_tables/639/data
And the second: https://software.sil.org/toolbox/
