### ISSUE TITLE
Questions section validation problem

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#84]
**Migrated from Trac:**

> - Original: <http://lemur.ling.washington.edu/trac/matrix/ticket/581>
> - Reporter: ebender
> - Created: 08/11/09 13:44:37
> - Updated: 08/11/09 13:44:37
> - Keywords: 
> - Notes:
>   - There may be formatting problems from the conversion
>   - Comments on tickets are *not* migrated! See the original issue.

Retrofit of questions section left hanging validation errors that currently don't put red stars in the right place.

**Comment by ajcassell** [comment]
The only oddity I could find with various combinations of choices for yes-no-questions was that the red asterisk is before the radio button for the first and last questions but I think this makes more sense than putting them before the beginning of the line. 
![Screen Shot 2024-10-06 at 6 09 03 PM](https://github.com/user-attachments/assets/f9fc9e36-5cff-4e23-b4b9-a7f9a5298068)
![Screen Shot 2024-10-06 at 6 09 03 PM](https://github.com/user-attachments/assets/e39b4ab6-d2ec-4fc5-89ed-40a56811af92)


As far as wh-questions, there was one issue I found and fixed - the error message was on the noun line instead of the adposition line for pied piping.
![Screen Shot 2024-10-06 at 6 18 20 PM](https://github.com/user-attachments/assets/b44d6eba-fc63-4cd0-8fa5-4de49064fc3b)

Fixed:
![Screen Shot 2024-10-06 at 6 18 35 PM](https://github.com/user-attachments/assets/f66ba8ba-7859-4bf2-953e-34c6ebb439a9)

**Comment by emilymbender** [comment]
I can't guess what that would have been -- and maybe it got cleaned up in the meantime.
